### PR TITLE
Use python3 when executing http server

### PR DESCRIPTION
**Pull request by Ryanf55**

### CODE REVIEW

**Comment by IamPete1** [comment]
Both work for me, does just using `python` cause issues somewhere?

If we decide to change then we should keep the vscode task upto date here: https://github.com/ArduPilot/WebTools/blob/dff6632176267fc4b5258c2d2f4558fa2466f662/.vscode/tasks.json#L7

**Comment by Ryanf55** [comment]
> Both work for me, does just using `python` cause issues somewhere?
> 
> If we decide to change then we should keep the vscode task upto date here:
> 
> https://github.com/ArduPilot/WebTools/blob/dff6632176267fc4b5258c2d2f4558fa2466f662/.vscode/tasks.json#L7

Good question. 

It's now recommended by the python devs to use the python3 naming as all OS's support that. Many OS's have stopped aliasing `python` to be `python3`, which includes Ubuntu 22 by default. 

See https://github.com/ArduPilot/ardupilot/pull/28055 for details

**Comment by Ryanf55** [comment]
> Both work for me, does just using `python` cause issues somewhere?
> 
> If we decide to change then we should keep the vscode task upto date here:
> 
> https://github.com/ArduPilot/WebTools/blob/dff6632176267fc4b5258c2d2f4558fa2466f662/.vscode/tasks.json#L7

Done and force pushed!

**Comment by IamPete1** [comment]
Thanks.

**Pull request merged**
