### PR TITLE
Add Magfit

### PR DESCRIPTION
**Pull request by IamPete1**
This adds a MAGFit tool 

https://youtu.be/yW8HtBqAJLQ?si=vFYPkC5uoFNVQfS7

There is a fair bit or re-work in other tools to maximize the amount of shared code.

I would like to get a WebTools landing page done before this is merged, otherwise it will just need re-directing when we move to that. 

This does not get exactly the same results as MAVExplorers MAGFit, mostly because this does not do this:

https://github.com/ArduPilot/pymavlink/blob/f508300142dcb313a95008a08e845b5acb192008/tools/magfit_WMM.py#L118-L122

This is faster because it does a direct matrix inversion rather than a iterative method. If we were to add stuff like the above MAVExplorer yaw adjustment we would need to move to a iterative method here, although I think we would need much few iterations with this method. 

I would like to add a orientation calculation/checking in the future for both the built in AP orientations and custom orientations.

### CODE REVIEW

**Comment by rmackay9** [comment]
Really great to see this tool on the web, not every user can run MAVProxy!

**Comment by IamPete1** [comment]
Added attitude source options,

image

A example benchmark against MAVExplorer. Results are essentially the same if the same attitude source is used. 
image

**Comment by IamPete1** [comment]
Now also checks and fixes orientations, pram is magically set but the details are printed in the console:

image

**Comment by IamPete1** [comment]
Also now does a offsets and scale fix without iron corrections.
image

**Comment by IamPete1** [comment]
Need to add error catching alert per the other tools.

**Comment by IamPete1** [comment]
- Fixed some bugs in the calculation for motor comp. 
- Added offsets only calc.
- Added the ability to do a motor calibration with just offsets, offsets and scale or offsets and iron.
- Added orientation check and option to fix
- Now fits all possible combinations up front

Still more to do, param display is broken currently, need to make the option to change the use param do something. Look into adding yaw change graph and length change graph.

image

**Comment by IamPete1** [comment]
Added to new landing page and fixed a few more bugs, 
image

**Comment by Williangalvani** [comment]
could we have an option of manually inputting gps coordinates? for the unlucky vehicles living under the sea? 😬

**Comment by IamPete1** [comment]
Rebased.

**Pull request merged**
